theme = "snazzy"

[editor]
auto-completion = true
line-number = "absolute"
auto-format = true
auto-info = true
bufferline = "always"
color-modes = true
completion-trigger-len = 3
text-width = 80
auto-pairs = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["file-modification-indicator", "mode", "spinner", "total-line-numbers", "workspace-diagnostics"]
center = ["file-type", "file-name"]
right = ["diagnostics", "selections", "position", "file-line-ending"]
separator = "|"

[keys.normal]
X = "extend_line_above"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
l = ":sh zellij action new-pane -fc -n 'lazygit' --height=80% --width=80% -x=10% -y=10% -- 'lazygit'"
i = ":sh zellij run -f -n 'yazi picker' --height=80% --width=80% -x=10% -y=10% -- '/Users/<>/.config/helix/scripts/yazi-picker.sh'"
