# theme = "snazzy"
# theme = "fleet_dark"
# theme = "carbon"
theme = "Revontuli-night"

[editor]
auto-completion = true
line-number = "relative"
auto-format = true
auto-info = true
bufferline = "multiple"
color-modes = true
completion-trigger-len = 2
auto-pairs = false
end-of-line-diagnostics = "hint"
cursorline = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
max-wrap = 15 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40
# wrap-indicator = ""  # set wrap-indicator to "" to hide it
# wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
X = "extend_line_above"
C-j = "save_selection"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
l = [
  ":sh zellij action new-pane -fc -n 'lazygit' --height='80%%' --width='80%%' -x='10%%' -y='10%%' -- 'lazygit'",
  ":reload-all",
  # ":sh zellij action toggle-floating-panes"
  ]
I = ":sh zellij run -f -n 'yazi picker' --height=80%% --width=80%% -x=10%% -y=10%% -- ~/.config/helix/scripts/yazi-picker.sh"
i = ":sh zellij run -f -n 'yazi picker' --height=80%% --width=80%% -x=10%% -y=10%% -- ~/.config/helix/scripts/yazi-picker.sh %|buffer_name|"
z = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name} | sed -E 's/[0-9]+).*//' | sed 's/(//g'}"


[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
