#cargo owl
# [language-server.cargo-owlsp]
# command = "cargo-owlsp"

# [[language]]
# name = "rust"
# auto-format = true
# language-servers = ["cargo-owlsp","rust-analyzer"]

[[language]]
name = "rust"
auto-format = true

[language.formatter]
command = 'rustfmt'
args = [ "--edition=2021" ]

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"
 
[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", initCommands = [ "command script import /opt/homebrew/Cellar/rust/1.85.0/lib/rustlib/etc/lldb_lookup.py", "command source -s 0 /opt/homebrew/Cellar/rust/1.85.0/lib/rustlib/etc/lldb_commands" ], runInTerminal = true }

[[language]]
name = "protobuf"
file-types = ["proto"]
auto-format = true
comment-token = "//"

[language.formatter]
command = 'clang-format'
args = [
  "--style={BasedOnStyle: Google, ColumnLimit: 80, DerivePointerAlignment: false, PointerAlignment: Left, AlignConsecutiveMacros: true, BinPackArguments: false, BinPackParameters: false, AllowShortFunctionsOnASingleLine: true, SpaceAfterCStyleCast: true, AllowShortBlocksOnASingleLine: false }"
]

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c"] # TODO: ["h"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
auto-format = false

[language.formatter]
command = 'clang-format'
args = [
  "--style={BasedOnStyle: Google, ColumnLimit: 80, DerivePointerAlignment: false, PointerAlignment: Left, AlignConsecutiveMacros: true, BinPackArguments: false, BinPackParameters: false, AllowShortFunctionsOnASingleLine: false, SpaceAfterCStyleCast: true, AllowShortBlocksOnASingleLine: false , IncludeBlocks: Regroup}"
]

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { console = "internalConsole", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { console = "internalConsole", pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { console = "internalConsole", attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[[grammar]]
name = "c"
source = { git = "https://github.com/tree-sitter/tree-sitter-c", rev = "7175a6dd5fc1cee660dce6fe23f6043d75af424a" }

[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
auto-format = false

[language.formatter]
command = 'clang-format'
args = [
  "--style={BasedOnStyle: Google, ColumnLimit: 80, DerivePointerAlignment: false, PointerAlignment: Left, AlignConsecutiveMacros: true, BinPackArguments: false, BinPackParameters: false, AllowShortFunctionsOnASingleLine: false, SpaceAfterCStyleCast: true, AllowShortBlocksOnASingleLine: false }"
]

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { console = "internalConsole", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { console = "internalConsole", pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { console = "internalConsole", attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[[language]]
name = "python"
auto-format = false

[language.formatter]
command = "black"
args = [
"-", # stdin
"--quiet",
"--line-length=79",
]

[[language]]
name = "css"
scope = "source.css"
injection-regex = "css"
file-types = ["css", "scss"]
roots = []
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "scss"
scope = "source.scss"
injection-regex = "scss"
file-types = ["scss"]
roots = []
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = ["json", "jsonc"]
roots = []
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "json"
source = { git = "https://github.com/tree-sitter/tree-sitter-json", rev = "73076754005a460947cafe8e03a8cf5fa4fa2938" }
